name: build

on: [push, pull_request]

jobs:
  deploy:
    name: Build and release
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: bazelbuild/setup-bazelisk@v2
    - name: Mount bazel cache
      uses: actions/cache@v3
      with:
        path: "~/.cache/bazel"
        key: bazel
    - name: Test
      run: bazel test //...
    - name: package
      run: bazel run //simple/service:push_service
